export default {
  ADD_AUTH_TOKEN: 'ADD_AUTH_TOKEN',
  DELETE_AUTH_TOKEN: 'DELETE_AUTH_TOKEN',
  DELETE_DEPLOYMENT: 'DELETE_DEPLOYMENT',
  SET_AUTH_TOKEN: 'SET_AUTH_TOKEN',
  SET_DEPLOYMENTS: 'SET_DEPLOYMENTS',
  SET_ERROR: 'SET_ERROR',
  UPDATE_DEPLOYMENT: 'UPDATE_DEPLOYMENT'
}
