export default {
  ADD_ALIAS: 'ADD_ALIAS',
  ADD_AUTH_TOKEN: 'ADD_AUTH_TOKEN',
  ADD_DEPLOYMENT_ALIAS: 'ADD_DEPLOYMENT_ALIAS',
  DELETE_ALIAS: 'DELETE_ALIAS',
  DELETE_AUTH_TOKEN: 'DELETE_AUTH_TOKEN',
  DELETE_DEPLOYMENT: 'DELETE_DEPLOYMENT',
  DELETE_DEPLOYMENT_ALIAS: 'DELETE_DEPLOYMENT_ALIAS',
  SET_AUTH_TOKEN: 'SET_AUTH_TOKEN',
  SET_ALIASES: 'SET_ALIASES',
  SET_DEPLOYMENTS: 'SET_DEPLOYMENTS',
  SET_DEPLOYMENT_ALIASES: 'SET_DEPLOYMENT_ALIASES',
  SET_ERROR: 'SET_ERROR',
  UPDATE_DEPLOYMENT: 'UPDATE_DEPLOYMENT'
}
